name: encrypt
version: 6.0.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
repository: https://github.com/adampermana/encrypt_v2.git
issue_tracker: https://github.com/adampermana/encrypt_v2/issues

executables:
  secure-random:

environment:
  flutter: '>=3.32.8'
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  args: ^2.7.0
  asn1lib: ^1.6.5
  clock: ^1.1.2
  collection: ^1.19.1
  crypto: ^3.0.6
  pointycastle: ^4.0.0
  random_x: ^0.3.1

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^6.0.0
  dartdoc: ^8.3.4
  coverage: ^1.15.0

false_secrets:
 - /test/*.pem
