name: encrypt
version: 6.0.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
repository: https://github.com/adampermana/encrypt_v2.git
issue_tracker: https://github.com/adampermana/encrypt_v2/issues

executables:
  secure-random:

environment:
  flutter: '>=3.22.0'
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  args: ^2.7.0
  asn1lib: ^1.5.8
  clock: ^1.1.1
  collection: ^1.18.0
  crypto: ^3.0.6
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

false_secrets:
 - /test/*.pem
